CREATE DATABASE db_food_service;

USE db_food_service;

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_categoria` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `DESCRICAO` varchar(45) NOT NULL,
  `ATIVO` tinyint NOT NULL DEFAULT '1',
  `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_produto` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_CATEGORIA` INT NOT NULL,
  `DESCRICAO` VARCHAR(100) NOT NULL,
  `ATIVO` TINYINT NOT NULL DEFAULT 1,
  `ESTOQUE_CONTROLADO` TINYINT NOT NULL DEFAULT 0,
  `DATA_CADASTRO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `ID_CATEGORIA`),
  CONSTRAINT `fk_tbl_produto_tbl_categoria`
    FOREIGN KEY (`ID_CATEGORIA`)
    REFERENCES `db_food_service`.`tbl_categoria` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_produto_valor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_PRODUTO` INT NOT NULL,
  `VALOR_CUSTO` DECIMAL(12,2) NOT NULL,
  `VALOR_VENDA` DECIMAL(12,2) NOT NULL,
  `ATIVO` TINYINT NOT NULL DEFAULT 1,
  `DATA_CADASTRO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `ID_PRODUTO`),
  CONSTRAINT `fk_tbl_valor_produto_tbl_produto`
    FOREIGN KEY (`ID_PRODUTO`)
    REFERENCES `db_food_service`.`tbl_produto` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_cliente` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `CPF` varchar(11) NOT NULL,
  `EMAIL` varchar(45) NOT NULL,
  `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_login` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` INT NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(500) NOT NULL,
  `PERFIL` VARCHAR(15) NOT NULL,
  `DATA_CADASTRO` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`, `ID_CLIENTE`),
  CONSTRAINT `fk_tbl_login_tbl_cliente`
    FOREIGN KEY (`ID_CLIENTE`)
    REFERENCES `db_food_service`.`tbl_cliente` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_telefone` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int NOT NULL,
  `NUMERO` varchar(45) NOT NULL,
  `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`,`ID_CLIENTE`),
  KEY `cliente_tlefone_idx` (`ID_CLIENTE`),
  CONSTRAINT `cliente_tlefone` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `tbl_cliente` (`id`)
);

CREATE TABLE IF NOT EXISTS `db_food_service`.`tbl_endereco` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `ID_CLIENTE` int NOT NULL,
  `LOGRADOURO` varchar(100) NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `COMPLEMENTO` varchar(100) NOT NULL,
  `BAIRRO` varchar(50) NOT NULL,
  `CIDADE` varchar(50) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  `CEP` varchar(8) NOT NULL,
  `DATA_CADASTRO` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`,`ID_CLIENTE`),
  KEY `fk_tbl_endereco_tbl_cliente` (`ID_CLIENTE`),
  CONSTRAINT `fk_tbl_endereco_tbl_cliente` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `tbl_cliente` (`id`)
) ;
